# Generated by Django 6.0.8 on 2026-08-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0004_goal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='category',
        ),
        migrations.AlterField(
            model_name='goal',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='goal',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='goal',
            name='target_date',
            field=models.DateField(),
        ),
    ]
