# Generated by Django 6.0.8 on 2026-09-11 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0006_goal_category_goal_image_alter_goal_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goal',
            name='category',
        ),
    ]
